openapi: 3.0.0

info:
  title: Test API
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1
    description: Local express server

tags:
  - name: Users
  - name: Auth

paths:
  /users:
    post:
      tags:
        - Users

      summary: Crear usuario
      description: Crea un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                bio:
                  type: string 
                  example: Hola mundo 
              required:
                - name
                - email   
      responses:
        '200':
          description: Operación exitosa!
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Bad Request

          content:
            application/json:

              schema:
                type: object

                properties:
                  data:
                    nullable: true
                    example: null

                  error:
                    type: string

                required:
                  - data
                  - error

              examples:
                emailRequerido:
                  summary: Email faltante
                  value:
                    data: null
                    error: El email es requerido

                nameRequerido:
                  summary: Name faltante
                  value:
                    data: null
                    error: El name es requerido

